language: node_js
script: npm test
node_js:
  - "6.0"

after_success:
  - npm run dist:release

addons:
  artifacts:
    s3_region: "eu-central-1"
    paths:
      - ./dist/*.js
    target_paths:
      - webshell.js
